{% set name = "airflow-balancer" %}
{% set version = "0.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-balancer/airflow_balancer-{{ version }}.tar.gz
  sha256: 7bf48ea0cd55fc8d1c81b7d8dd6a23e8eb3e1c4c1f1697939ab34be4141b2891

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.8,<3
    - apache-airflow-providers-ssh
    - airflow-config
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_balancer

about:
  home: https://github.com/airflow-laminar/airflow-balancer
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Utilities for load balancing DAGs
  description: Utilities for load balancing DAGs
  dev_url: https://github.com/airflow-laminar/airflow-balancer

extra:
  recipe-maintainers:
    - timkpaine
