{% set name = "airflow-balancer" %}
{% set version = "0.7.7" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-balancer/airflow_balancer-{{ version }}.tar.gz
  sha256: 856bc7c0115bf26da3c70f55c5b0f55d5261892217e95ea576e95952f42ce984

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - nodejs
    - pip
    - pnpm
  run:
    - python >={{ python_min }}
    - airflow-config >=1.10,<1.11
    - airflow-pydantic >=1.4,<1.6
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_balancer

about:
  home: https://github.com/airflow-laminar/airflow-balancer
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Utilities for load balancing DAGs
  description: Utilities for load balancing DAGs
  dev_url: https://github.com/airflow-laminar/airflow-balancer

extra:
  recipe-maintainers:
    - timkpaine
