{% set name = "airflow-balancer" %}
{% set version = "0.7.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-balancer/airflow_balancer-{{ version }}.tar.gz
  sha256: 9e23e4b598247ae72394c45b3c4a0ecef5dfce8c10d5be5173659ff5322d8341

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - nodejs
    - pip
    - pnpm
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.8,<3
    - apache-airflow-providers-ssh
    - airflow-config >=1.10,<1.11
    - hydra-core
    - omegaconf
    - pkn >=0.1.3
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_balancer

about:
  home: https://github.com/airflow-laminar/airflow-balancer
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Utilities for load balancing DAGs
  description: Utilities for load balancing DAGs
  dev_url: https://github.com/airflow-laminar/airflow-balancer

extra:
  recipe-maintainers:
    - timkpaine
